---
- name: Create EC2 instance
  ec2:
    key_name: "{{ aws_key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_image_id }}"
    region: "{{ aws_region }}"
    wait: yes
    count: 1
    vpc_subnet_id: "{{ aws_subnet_id }}"
    group: "{{ aws_security_group }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ aws_instance_name }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  loop: "{{ ec2.instances }}"

- name: Deploy JAR artifact to the instance
  copy:
    src: "{{ jar_artifact_path }}"
    dest: "/home/ec2-user/app.jar"
  delegate_to: "{{ item.public_ip }}"
  loop: "{{ ec2.instances }}"

- name: Start the application
  shell: "nohup java -jar /home/ec2-user/app.jar &"
  args:
    chdir: /home/ec2-user
  delegate_to: "{{ item.public_ip }}"
  loop: "{{ ec2.instances }}"

